//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNationalBankApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanNo { get; set; }
        public decimal LoanAmount { get; set; }
        public int AccNo { get; set; }
        public decimal LoanInterest { get; set; }
        public System.DateTime RepaymentDate { get; set; }
        public System.DateTime LoanStartDate { get; set; }
        public decimal LoanRepayment { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
